### ISSUE TITLE
Bug in removing students from a team

### ISSUE THREAD

**Issue by chinmay314** [wolfe3d/sodata#22]
When a student is removed from a team in the "edit team" menu, they aren't actually removed from the teammateplace table. The only way to completely remove them from the teammateplace table is to remove all of their events in the "assign events" menu BEFORE removing them in the "edit team" menu. 

Removing them from the team should ideally also remove all of their events - i will look into fixing this behavior.

**Comment by chinmay314** [comment]
Okay so I'm not sure how you want this to be handled, but to me it seems that the problem boils down to the fact that when tournamentteamadjust is being called, it only removes the entry from teammate, but not teammate place.

Is there a reason that tournamentteamadjust deletes from a variable $table but tournamenteventteammateadjust deletes from teammateplace explicitly?

**Comment by wolfe3d** [comment]
You should not be removing students.  This should only be done by me.  You should just change students to INACTIVE.

Doug Wolfe
Build Your Own Jeopardy

From: Chinmay J
Sent: Sunday, September 5, 2021 6:19 PM
To: wolfe3d/sodata
Cc: Subscribed
Subject: [wolfe3d/sodata] Bug in removing students from a team (#22)

When a student is removed from a team in the "edit team" menu, they aren't actually removed from the teammateplace table. The only way to completely remove them from the teammateplace table is to remove all of their events in the "assign events" menu BEFORE removing them in the "edit team" menu.
Removing them from the team should ideally also remove all of their events - i will look into fixing this behavior.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wolfe3d** [comment]
I am not sure that removing a student completely before removing their events is an ideal change in behavior.  What if you accidently click on a student?  I think an ideal behavior would be a warning (on clicking a student) that states that a student cannot be removed until the events are reassigned.  Then do not allow the unchecking of the box.

**Comment by wolfe3d** [comment]
I highlighted where these warnings and checks need to be done in tournamentteammateadjust.php and data.js
